name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every minute 
    - cron: '* * * * *'

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: speedbuild98/speedbuild98@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
